apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: cluster-dev
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
  datacenterRef:
    kind: DockerDatacenterConfig
    name: cluster-dev
  externalEtcdConfiguration:
    count: 3
  kubernetesVersion: "1.22"
  managementCluster:
    name: cluster-dev
  workerNodeGroupConfigurations:
  - count: 2
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: cluster-dev
  namespace: default
spec: {}

---
